# This rule is not used by the project external-haproxy-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to external-haproxy-operator.ullberg.us resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: external-haproxy-operator
    app.kubernetes.io/managed-by: kustomize
  name: backend-viewer-role
rules:
- apiGroups:
  - external-haproxy-operator.ullberg.us
  resources:
  - backends
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - external-haproxy-operator.ullberg.us
  resources:
  - backends/status
  verbs:
  - get
