---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - external-haproxy-operator.ullberg.us
  resources:
  - backends
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - external-haproxy-operator.ullberg.us
  resources:
  - backends/finalizers
  verbs:
  - update
- apiGroups:
  - external-haproxy-operator.ullberg.us
  resources:
  - backends/status
  verbs:
  - get
  - patch
  - update
