name: PR Check

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Install pre-commit
        run: apt -y install pre-commit

      - name: Check commits
        run: pre-commit run --hook-stage manual
